name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Fix Gradle permissions
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: anicore-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
